In [296]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [297]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [298]:
df.shape

(569, 33)

In [299]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [300]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [301]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [302]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

X_test

array([[ 1.510229  , -0.12785941,  1.48690918, ...,  1.40478863,
         0.61147809,  0.33416845],
       [-0.19884576, -0.2501076 , -0.22725249, ..., -0.54713194,
        -0.36662656, -0.96654454],
       [-0.32724036,  0.5774186 , -0.1900779 , ...,  1.40478863,
         2.46122702,  1.25915595],
       ...,
       [ 1.87829351,  2.76378044,  1.80082794, ...,  0.78793927,
        -0.05057233, -0.09345581],
       [ 0.97667811, -1.01415878,  0.94581236, ...,  0.4756689 ,
        -0.23687798, -0.25509886],
       [-0.70957094, -0.53927159, -0.76008829, ..., -1.10844947,
        -0.27846406, -0.84652863]], shape=(114, 30))

In [303]:
X_train

array([[-0.32724036,  1.35557534, -0.39205984, ..., -0.8532492 ,
        -0.98542746, -1.13521555],
       [-0.48416709, -0.86134855, -0.39371205, ...,  0.91407804,
         1.80749381,  2.18900895],
       [-0.05333189, -0.54397344, -0.02774886, ...,  0.34953013,
         0.28211632, -0.2345556 ],
       ...,
       [-0.26732288,  1.38378646, -0.33051524, ..., -0.84032767,
        -0.75587228, -0.86653128],
       [ 0.34897119,  0.79840571,  0.33449687, ...,  0.50643445,
        -0.56956664, -0.84490679],
       [-0.29585502, -0.89426152, -0.20205638, ...,  1.29095608,
         0.41352834,  3.05939462]], shape=(455, 30))

In [304]:
y_test

487    M
93     B
8      M
437    B
88     B
      ..
65     M
100    M
265    M
29     M
350    B
Name: diagnosis, Length: 114, dtype: str

In [305]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [306]:
y_test

array([1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 0])

In [307]:
#numpy to tensor
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [308]:
X_train_tensor

tensor([[-0.3272,  1.3556, -0.3921,  ..., -0.8532, -0.9854, -1.1352],
        [-0.4842, -0.8613, -0.3937,  ...,  0.9141,  1.8075,  2.1890],
        [-0.0533, -0.5440, -0.0277,  ...,  0.3495,  0.2821, -0.2346],
        ...,
        [-0.2673,  1.3838, -0.3305,  ..., -0.8403, -0.7559, -0.8665],
        [ 0.3490,  0.7984,  0.3345,  ...,  0.5064, -0.5696, -0.8449],
        [-0.2959, -0.8943, -0.2021,  ...,  1.2910,  0.4135,  3.0594]],
       dtype=torch.float64)

In [309]:
#difinig the neural network architecture

class SimpleNN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
        self.bias = torch.zeros(1, dtype=torch.float64, requires_grad=True)

    def forward(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        return torch.sigmoid(z)
    
    def loss_function(self, y_pred, y):
        # Clamp predictions to avoid log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

        # Calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
        return loss

In [310]:
learning_rate = 0.1
epochs = 25

In [311]:
#traning pipeline
# model = SimpleNN(X_train_tensor)
# model.weights

# #on loop
# for epochs in range(epochs):
#     # forward pass
#     ypred = model.forward(X_train_tensor)

   
#     # loss calculation

#     loss = model.loss_function(ypred, y_train_tensor)
    
#     # backward pass
#     loss.backward()

#     # parameter update
#     with torch.no_grad():
#         model.weights -= learning_rate * model.weights.grad
#         model.bias -= learning_rate * model.bias.grad

#     # zero the gradients after updating
#     model.weights.grad.zero_()
#     model.bias.grad.zero_()

#     print(f"Epoch {epochs+1}/{epochs}, Loss: {loss.item()}")

In [312]:
# with torch.no_grad():
#     ypred = model.forward(X_test_tensor)
#     y_pred = (ypred > 0.5).float()  # Convert probabilities to binary predictions
#     accuracy = (y_pred == y_test_tensor).float().mean()

#     print(f"Test accuracy: {accuracy.item() * 100:.2f}%")

In [313]:
import torch.nn as nn
# create model with nn.Module
class NewModel(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()
    
    def forward(self, features):
        out = self.linear(features)
        return self.sigmoid(out)

In [314]:
loss_function = nn.BCELoss()

In [315]:
#traning pipeline
newmodel = NewModel(X_train_tensor.shape[1])
print(next(newmodel.parameters()).dtype)  #

optimizer = torch.optim.SGD(newmodel.parameters(), lr=learning_rate)


#on loop
for epochs in range(epochs):
    # forward pass
    ypred = newmodel(X_train_tensor.to(torch.float32))
   
    # loss calculation
    loss = loss_function(ypred, y_train_tensor.to(torch.float32).view(-1,1))
    
    optimizer.zero_grad()

    # backward pass
    loss.backward()

    # parameter update
    optimizer.step()

    # zero the gradients after updating
   

    print(f"Epoch {epochs+1}/{epochs}, Loss: {loss.item()}")

torch.float32
Epoch 1/0, Loss: 0.5919791460037231
Epoch 2/1, Loss: 0.47000524401664734
Epoch 3/2, Loss: 0.40202596783638
Epoch 4/3, Loss: 0.3579334318637848
Epoch 5/4, Loss: 0.3264940083026886
Epoch 6/5, Loss: 0.3026593327522278
Epoch 7/6, Loss: 0.28380250930786133
Epoch 8/7, Loss: 0.26840901374816895
Epoch 9/8, Loss: 0.25553786754608154
Epoch 10/9, Loss: 0.24457035958766937
Epoch 11/10, Loss: 0.23508122563362122
Epoch 12/11, Loss: 0.2267674058675766
Epoch 13/12, Loss: 0.21940626204013824
Epoch 14/13, Loss: 0.2128303050994873
Epoch 15/14, Loss: 0.20691059529781342
Epoch 16/15, Loss: 0.2015461027622223
Epoch 17/16, Loss: 0.19665637612342834
Epoch 18/17, Loss: 0.1921764314174652
Epoch 19/18, Loss: 0.18805310130119324
Epoch 20/19, Loss: 0.18424242734909058
Epoch 21/20, Loss: 0.180707648396492
Epoch 22/21, Loss: 0.1774177849292755
Epoch 23/22, Loss: 0.17434649169445038
Epoch 24/23, Loss: 0.1714712530374527
Epoch 25/24, Loss: 0.1687726080417633

In [316]:
newmodel.linear.weight

Parameter containing:
tensor([[ 0.2773,  0.0309,  0.3599,  0.1999,  0.1835,  0.1111,  0.0010,  0.1815,
          0.1113, -0.2062,  0.1603,  0.0545,  0.2194,  0.2346,  0.1503, -0.0996,
          0.0458, -0.0514, -0.0950, -0.0406,  0.4093,  0.2375,  0.0903,  0.2155,
          0.0635,  0.2800,  0.2877,  0.3845,  0.1098,  0.2243]],
       requires_grad=True)

In [317]:
with torch.no_grad():
    ypred = newmodel.forward(X_test_tensor.to(torch.float32))
    y_pred = (ypred > 0.5).float()  # Convert probabilities to binary predictions
    accuracy = (y_pred == y_test_tensor).float().mean()

    print(f"Test accuracy: {accuracy.item() * 100:.2f}%")

Test accuracy: 53.94%